Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  MaxSlashes: 0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19
  Exclude:
    - '**/Rakefile*'
    - '**/*.rake'

Style/HashSyntax:
  EnforcedStyle: hash_rockets
  Include:
    - '**/Rakefile*'
    - '**/*.rake'
